name: Compile Flutter Engine - Android ARM64 Host (Release Only - Latest Stable)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-arm64-host:
    name: Build Android ARM64 Host Engine (Release)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_mode: [ release ] # Only build the release variant

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: flutter/flutter
          path: flutter
          fetch-depth: 1
          lfs: true

      - name: Get Flutter Dependencies
        run: |
          cd flutter
          ./bin/flutter doctor -v

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '33'
          ndk-version: '25.1.8937393'

      - name: Install NDK and CMake
        run: |
          yes | sdkmanager --install "ndk;25.1.8937393"
          yes | sdkmanager --install "cmake;3.22.1"

      - name: Install python3
        run: sudo apt-get install -y python3

      - name: Install dependencies
        run: | 
          yes | sudo apt-get update
          yes | sudo apt-get install -y build-essential

      - name: Install Depot Tools
        uses: newkdev/setup-depot-tools@v1.0.1

      - name: Configure Flutter Engine Build (release)
        run: |
          cd flutter/engine
          echo "Current directory after cd flutter/engine: $(pwd)"
          ./src/flutter/tools/gn --android --android-cpu=arm64
          echo "GN configuration complete."

      - name: Create Output Directories (release)
        run: |
          cd flutter/engine/out/linux_arm64
          echo "Current directory: $(pwd)"
          mkdir -p release
          echo "Output directories created."
          ls -l

      - name: Build Flutter Engine (release)
        run: |
          cd flutter/engine
          echo "Current directory before ninja: $(pwd)"
          ninja -C out/linux_arm64/release flutter_patched_sdk
          echo "Ninja build complete."
          echo "Contents of out/linux_arm64/release:"
          ls -l out/linux_arm64/release

      - name: Print Artifact Path (release)
        run: |
          echo "Expected artifact path for release: ${{ github.workspace }}/flutter/engine/out/linux_arm64/release/flutter_patched_sdk"
