name: Build Flutter Engine for ARM64 (Host and Target)

on:
  push:
    branches:
      - main  # Trigger the build when you push to the main branch
  pull_request:
    branches:
      - main  # Trigger the build for pull requests targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions runner that supports Ubuntu Linux

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checkout the repository

    - name: Set up Java JDK
      uses: actions/setup-java@v2
      with:
        java-version: '8'  # Setup Java 8 for Android build
        java-package: jdk  # Setup the required Java package

    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          clang \
          python3 \
          build-essential \
          libglib2.0-dev \
          libfreetype6-dev \
          libssl-dev \
          pkg-config \
          libprotobuf-dev \
          protobuf-compiler \
          libcurl4-openssl-dev \
          libpng-dev \
          cmake \
          ninja-build \
          python3-pip \
          wget

    - name: Install Dart SDK
      run: |
        # Install Dart SDK for compatibility
        sudo apt-get install apt-transport-https
        sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable_amd64.deb'
        sudo apt-get update -y
        sudo apt-get install dart

    - name: Set up Android NDK
      run: |
        export ANDROID_HOME=$HOME/Android/Sdk
        export PATH=$ANDROID_HOME/tools:$ANDROID_HOME/tools/bin:$ANDROID_HOME/platform-tools:$PATH
        wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
        unzip android-ndk-r21e-linux-x86_64.zip -d $HOME/Android/Sdk
        export ANDROID_NDK_HOME=$HOME/Android/Sdk/android-ndk-r21e
        export PATH=$ANDROID_NDK_HOME:$PATH

    - name: Set up Android SDK (for building APK)
      run: |
        wget https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip
        unzip commandlinetools-linux-7583922_latest.zip -d $HOME/Android/Sdk/cmdline-tools
        export ANDROID_SDK_ROOT=$HOME/Android/Sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --licenses
        sdkmanager "build-tools;30.0.3" "platform-tools"

    - name: Clone Flutter Engine
      run: |
        git clone https://github.com/flutter/engine.git
        cd engine
        git checkout master  # or use the Flutter version you are targeting

    - name: Configure for ARM64 Host and Target
      run: |
        cd engine
        # Set environment variables for ARM64 host and target
        export GN_ARGS="target_os=android target_cpu=arm64 android_ndk=$ANDROID_NDK_HOME"
        ./flutter/tools/gn $GN_ARGS
        # Confirm that the target is ARM64
        cat out/host_debug/gn_args.gn

    - name: Build the Engine for ARM64 Target
      run: |
        cd engine
        # Build the engine with ninja for ARM64 target
        ninja -C out/android_arm64

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: flutter-engine-arm64
        path: engine/out/android_arm64  # Path to the compiled engine binaries

    - name: Clean up
      run: |
        rm -rf engine  # Clean up the engine repository
