name: Compile Flutter Engine - Android ARM64 Host (Release Only - Specific Version)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-android-arm64-host:
    name: Build Android ARM64 Host Engine (Release)
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_mode: [ release ] # Only build the release variant
        # build_mode: [ debug, profile, release ] # Previous configuration

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: flutter/flutter
          path: flutter
          fetch-depth: 1
          lfs: true

      - name: Checkout latest stable Flutter version
        run: |
          cd flutter
          git fetch --tags
          git checkout -f v3.19.1 # Replace with the actual latest stable tag
          echo "Checked out Flutter version: $(git --no-pager log -n 1 --pretty=format:'%H %s')"

      - name: Verify Git HEAD
        run: |
          cd flutter
          git rev-parse HEAD

      - name: Get Flutter Dependencies
        run: |
          cd flutter
          ./bin/flutter doctor -v

      - name: Set up Java Development Kit (JDK)
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          sdk-version: '33'
          ndk-version: '25.1.8937393'

      - name: Install NDK and CMake
        run: |
          echo "sdkmanager --install 'ndk;${ANDROID_NDK_VERSION}'" | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --stdin
          echo "sdkmanager --install 'cmake;3.22.1'" | sdkmanager --sdk_root="${ANDROID_SDK_ROOT}" --stdin

      - name: Configure Flutter Engine Build (release)
        run: |
          cd flutter/engine
          echo "Current directory after cd flutter/engine: $(pwd)"
          ./flutter/tools/gn --host-os=linux --host-cpu=arm64 --target-os=android --target-cpu=arm64 --runtime-mode=release --optimized
          echo "GN configuration complete."

      - name: Create Output Directories (release)
        run: |
          cd flutter/engine/out/linux_arm64
          echo "Current directory: $(pwd)"
          mkdir -p release
          echo "Output directories created."
          ls -l

      - name: Build Flutter Engine (release)
        run: |
          cd flutter/engine
          echo "Current directory before ninja: $(pwd)"
          ninja -C out/linux_arm64/release flutter_patched_sdk
          echo "Ninja build complete."
          echo "Contents of out/linux_arm64/release:"
          ls -l out/linux_arm64/release

      - name: Print Artifact Path (release)
        run: |
          echo "Expected artifact path for release: ${{ github.workspace }}/flutter/engine/out/linux_arm64/release/flutter_patched_sdk"

      # - name: Create Archive (release)
      #   run: |
      #     cd ${{ github.workspace }}/flutter/engine/out/linux_arm64
      #     zip -r android-arm64-host-engine-release.zip release

      # - name: Upload Archive Artifact (release)
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: android-arm64-host-engine-release
      #     path: ${{ github.workspace }}/flutter/engine/out/linux_arm64/android-arm64-host-engine-release.zip
      #     if-no-files-found: error
